# Generated by Django 4.0.2 on 2022-02-16 13:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='overview',
            field=models.CharField(help_text='Enter a brief descripton of the news', max_length=500),
        ),
    ]
